#!/usr/bin/env bash
# check-disk-alerts.sh — disk-usage monitor for the relay.
#
# Runs from cron every couple of hours. If any "interesting" partition is at
# or above THRESHOLD%, appends a single line to /root/.claude/system-alerts.md.
# Root Claude is instructed (via /root/CLAUDE.md) to read that file at session
# start and surface anything fresh to the user.
#
# Usage: check-disk-alerts.sh [threshold]   (default 90)
#
# Intentionally minimal — no rotation/dedup logic. The file is append-only;
# users can clear it whenever (`> /root/.claude/system-alerts.md`).

set -euo pipefail

ALERTS_FILE=/root/.claude/system-alerts.md
THRESHOLD=${1:-90}
TS=$(date -u +%Y-%m-%dT%H:%M:%SZ)

install -d -m 0700 /root/.claude

# Initial header if file doesn't exist
if [[ ! -f "$ALERTS_FILE" ]]; then
  cat > "$ALERTS_FILE" <<'HDR'
# System alerts

Generated by check-disk-alerts.sh on the relay. Root Claude reads this at
session start and surfaces today's entries to the user. Safe to truncate
manually after reviewing: `> /root/.claude/system-alerts.md`.

HDR
fi

# Only check real, non-tmpfs filesystems; df's -x excludes types.
df -h -x tmpfs -x devtmpfs -x overlay -x squashfs --output=target,pcent,used,size \
  | tail -n +2 \
  | while read -r mount pcent used size; do
      pct=${pcent%\%}
      [[ "$pct" =~ ^[0-9]+$ ]] || continue
      if [[ "$pct" -ge "$THRESHOLD" ]]; then
        printf -- '- %s  ⚠ %s at %s%%  (%s of %s used)\n' \
          "$TS" "$mount" "$pct" "$used" "$size" >> "$ALERTS_FILE"
      fi
    done

exit 0
